apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: wilconsadocker/nodejs
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: my-reg-cred

---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: my-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodeport: 30000
  selector:
    app: my-app


